### ISSUE TITLE
Make compatible with loadMoreItems

### ISSUE THREAD

**Issue by leocaseiro** [rajivnarayana/nativescript-sectioned-list-view#3]
Hi, thank you for your amazing plugin. I'm using with my lists and I was wondering if there's any way to make possible work with [loadMoreItems](http://docs.nativescript.org/api-reference/classes/_ui_list_view_.listview.html#loadmoreitemsevent).

I believe it's a wrapper of Repeater and I couldn't find repeater with loadMoreItems as well.

My list is over 8000 registers, so I really need some kind of pagination here...

**Comment by leocaseiro** [comment]
For the moment, I've implemented with this [solution](https://groups.google.com/d/msg/nativescript/KAJICjey2uk/lM8GlIHYAwAJ) if someone is interested.

``` javascript
var gestures = require('ui/gestures');
function onLoaded(args) {
    page = args.object;
    page.bindingContext = pageData;

    var scrollView = page.getViewById('scrollView');
    scrollView.on(gestures.GestureTypes.swipe, function(args) {
        if (args.direction === 4) { //down
            // loadMoreItems();
        }
    });
}
```

``` xml
<tools:SectionedListView id="scrollView" items="{{items}}" itemTap="onTap" rowHeight="60" headerHeight="26" >...</tools:SectionedListView>
```

**Comment by rajivnarayana** [comment]
That is certainly a good thing to have. I am guessing it should be simple enough.

**Comment by rajivnarayana** [comment]
@leocaseiro The fix worked in my local. Hope it does for you too. This is not a wrapper of Repeater but of a ListView so it inherits all the cell reusability from the latter. Glad to know this plugin works with 8000 items. Thats one long list you have !

However, I am guilty of not bringing in the latest changes to ListView plugin. Will try to do that some time.

**Comment by leocaseiro** [comment]
Perfect! Thank you so much!
Worked like a charm...

PS: Yeap! 8000 items pretty cool!
